GET http://localhost:3000/todos/?status=TO%20DO
###
GET http://localhost:3000/todos/1

###
POST http://localhost:3000/todos
Content-Type: application/json

{
  "id": 7,
  "todo": "Do practice of python",
  "priority": "HIGH",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-13-22"
}